<h1 class="h3 mb-3">Categorías y subcategorías</h1>
<div class="row g-4">
  <div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">Nueva categoría</h2><form method="post" action="?route=category_save" class="row g-2"><div class="col-7"><input name="nombre" class="form-control" placeholder="ALIMENTACION" required></div><div class="col-5"><select name="tipo_default" class="form-select"><option value="gasto">Gasto</option><option value="ingreso">Ingreso</option><option value="ambos">Ambos</option></select></div><div class="col-12"><button class="btn btn-primary">Guardar</button></div></form></div></div></div>
  <div class="col-lg-7"><div class="card"><div class="card-body"><h2 class="h5">Nueva subcategoría</h2><form method="post" action="?route=subcategory_save" class="row g-2"><div class="col-md-5"><select name="categoria_id" class="form-select" required><?php foreach ($categories as $c): ?><option value="<?= $c['id'] ?>"><?= e($c['nombre']) ?></option><?php endforeach; ?></select></div><div class="col-md-5"><input name="nombre" class="form-control" placeholder="MERCADONA" required></div><div class="col-md-2"><button class="btn btn-primary w-100">Guardar</button></div></form></div></div></div>
</div>
<div class="row g-4 mt-1">
  <div class="col-lg-5"><div class="card"><div class="card-body"><h2 class="h5">Categorías</h2><table class="table"><thead><tr><th>Nombre</th><th>Tipo</th><th></th></tr></thead><tbody><?php foreach ($categories as $c): ?><tr><td><form class="d-flex gap-2" method="post" action="?route=category_save"><input type="hidden" name="id" value="<?= $c['id'] ?>"><input name="nombre" value="<?= e($c['nombre']) ?>" class="form-control form-control-sm"></td><td><select name="tipo_default" class="form-select form-select-sm"><option value="gasto" <?= $c['tipo_default']==='gasto'?'selected':'' ?>>Gasto</option><option value="ingreso" <?= $c['tipo_default']==='ingreso'?'selected':'' ?>>Ingreso</option><option value="ambos" <?= $c['tipo_default']==='ambos'?'selected':'' ?>>Ambos</option></select></td><td><button class="btn btn-sm btn-outline-primary">Editar</button></form><form method="post" action="?route=category_delete" data-confirm="¿Eliminar categoría?" class="d-inline"><input type="hidden" name="id" value="<?= $c['id'] ?>"><button class="btn btn-sm btn-outline-danger">Eliminar</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div>
  <div class="col-lg-7"><div class="card"><div class="card-body"><h2 class="h5">Subcategorías</h2><table class="table"><thead><tr><th>Categoría</th><th>Nombre</th><th></th></tr></thead><tbody><?php foreach ($subcategories as $s): ?><tr><form method="post" action="?route=subcategory_save"><input type="hidden" name="id" value="<?= $s['id'] ?>"><td><select name="categoria_id" class="form-select form-select-sm"><?php foreach ($categories as $c): ?><option value="<?= $c['id'] ?>" <?= $c['id']==$s['categoria_id']?'selected':'' ?>><?= e($c['nombre']) ?></option><?php endforeach; ?></select></td><td><input name="nombre" value="<?= e($s['nombre']) ?>" class="form-control form-control-sm"></td><td><button class="btn btn-sm btn-outline-primary">Editar</button></form><form method="post" action="?route=subcategory_delete" data-confirm="¿Eliminar subcategoría?" class="d-inline"><input type="hidden" name="id" value="<?= $s['id'] ?>"><button class="btn btn-sm btn-outline-danger">Eliminar</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</div>
