<div class="d-flex justify-content-between mb-3"><h1 class="h3">Movimientos</h1><a class="btn btn-primary" href="?route=movement_form">Añadir manual</a></div>
<form class="row g-2 mb-3" data-dependent-scope>
  <input type="hidden" name="route" value="movements">
  <div class="col-md-3"><input name="q" value="<?= e($_GET['q'] ?? '') ?>" class="form-control" placeholder="Buscar concepto"></div>
  <div class="col-md-2"><input type="date" name="desde" value="<?= e($_GET['desde'] ?? '') ?>" class="form-control"></div>
  <div class="col-md-2"><input type="date" name="hasta" value="<?= e($_GET['hasta'] ?? '') ?>" class="form-control"></div>
  <div class="col-md-2"><select name="categoria_id" class="form-select" data-category-select><option value="">Categoría</option><?php foreach ($categories as $c): ?><option value="<?= $c['id'] ?>" <?= ($_GET['categoria_id'] ?? '')==$c['id']?'selected':'' ?>><?= e($c['nombre']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-2"><select name="subcategoria_id" class="form-select" data-subcategory-select data-subcategories-source="movement-filters-subcategories-data" data-placeholder="Subcategoría"><option value="">Subcategoría</option><?php foreach ($subcategories as $s): ?><option value="<?= $s['id'] ?>" <?= ($_GET['subcategoria_id'] ?? '')==$s['id']?'selected':'' ?>><?= e($s['nombre']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-1"><button class="btn btn-outline-primary w-100">Filtrar</button></div>
  <div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="pendiente" value="1" <?= !empty($_GET['pendiente'])?'checked':'' ?>> Solo pendientes</label></div>
</form>
<div class="card"><div class="table-responsive"><table class="table table-striped mb-0"><thead><tr><th>Fecha</th><th>Concepto</th><th>Tipo</th><th>Categoría</th><th>Origen</th><th class="text-end">Importe</th><th></th></tr></thead><tbody><?php foreach ($movements as $m): ?><tr><td><?= e($m['fecha']) ?></td><td><?= e($m['concepto_banco']) ?><?php if ($m['pendiente_revision']): ?><span class="badge text-bg-warning ms-1">pendiente</span><?php endif; ?></td><td><?= e($m['tipo']) ?></td><td><?= e(($m['categoria'] ?? '-') . ' / ' . ($m['subcategoria'] ?? '-')) ?></td><td><?= e($m['origen']) ?></td><td class="text-end <?= $m['tipo']==='ingreso'?'amount-income':'amount-expense' ?>"><?= money($m['importe']) ?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="?route=movement_form&id=<?= $m['id'] ?>">Editar</a><form method="post" action="?route=movement_delete" data-confirm="¿Eliminar movimiento?" class="d-inline"><input type="hidden" name="id" value="<?= $m['id'] ?>"><button class="btn btn-sm btn-outline-danger">Eliminar</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card mt-3"><div class="card-body d-flex justify-content-between align-items-center"><strong>Total visible (importe)</strong><span class="fs-5 <?= $totalImporte >= 0 ? 'amount-income' : 'amount-expense' ?>"><?= money($totalImporte) ?></span></div></div>
<script type="application/json" id="movement-filters-subcategories-data"><?= json_encode(array_map(fn ($s) => ['id' => (int) $s['id'], 'nombre' => $s['nombre'], 'categoria_id' => (int) $s['categoria_id']], $subcategories), JSON_UNESCAPED_UNICODE) ?></script>
